# Generated by Django 5.2.7 on 2025-11-05 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_jobapplication_cover_letter_jobapplication_cv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='salary_range',
            field=models.CharField(blank=True, help_text='e.g., £40,000 - £55,000', max_length=100),
        ),
    ]
